### ISSUE TITLE
CAExperimenter class changes

### ISSUE THREAD

**Issue by btstillman** [andrewpenland/CAExperiment#3]
some basic functionalities: convert rule table lookup to be based on a dictionary (so we don’t have to call bin_to_dec repeatedly, only once when the lookup table is created), have option for hex, extend current functions to arbitrary alphabets, take function in addition to rule table or rule number, read more options (.csv file, etc.) as input configurations, documentation, create a corresponding .tex template that matches experiment format for consistent and quick lab reports…i.e. a person can run an experiment just by filling out a form.

**Comment by andrewpenland** [comment]
We are going to address this by taking these as separate issues.
